### ISSUE TITLE
magnet

### ISSUE THREAD

**Issue by fawwaz1234** [zPeanut/Hydrogen#5] opened 2021-02-22 02:20 UTC
if u stand near a block it will pull u to the block

**Comment by zPeanut** [comment] 2021-02-22 17:50
can you provide video footage of this happening`?

**Comment by fawwaz1234** [comment] 2021-02-23 02:39
https://streamable.com/ssvm19

**Comment by zPeanut** [comment] 2021-02-23 11:08
what modules do you have enabled?

**Comment by fawwaz1234** [comment] 2021-02-23 12:58
none

**Comment by zPeanut** [comment] 2021-02-23 15:00
https://streamable.com/zwhf33 i cant really reproduce it, does it always happen or does it also happen when the mod is not installed?

**Comment by fawwaz1234** [comment] 2021-02-23 23:49
yes, i think i'll keep using 1.4 b2 for now

**Comment by zPeanut** [comment] 2021-02-24 14:02
try running hydrogen as a stand alone mod because i could not see any reason why this could come up. (i.e. in forge alone)

**Comment by fawwaz1234** [comment] 2021-02-25 01:24
still not working {optifine+hydrogen)

**Comment by fawwaz1234** [comment] 2021-02-25 02:03
i even ran it on multimc to test it still doesnt work

**Comment by fawwaz1234** [comment] 2021-02-25 02:04
i suggest u try running 1.4 on ur minecraft

**Comment by fawwaz1234** [comment] 2021-02-25 03:41
reinstalled it still not working hmm

**Comment by fawwaz1234** [comment] 2021-02-25 03:43
1.4 b2 works fine tho

**Comment by zPeanut** [comment] 2021-02-25 07:57
is 1.4.1 working?

**Comment by fawwaz1234** [comment] 2021-02-25 07:59
nope still having the same issue

**Comment by zPeanut** [comment] 2021-02-26 13:23
should be fixed in 1.4.2.

**Closed by zPeanut** 2021-02-26 13:23 UTC
