### ISSUE TITLE
Random crashes in singleplayer (not tried multiplayer yet)

### ISSUE THREAD

**Issue by Sobek88** [zPeanut/Hydrogen#51] opened 2022-04-14 16:45 UTC
I was testing the client in singleplayer Minecraft and noticed that the key to open up the GUI was LSHIFT. I tried to bind it to RSHIFT, which is the traditional GUI key, but when I attempted to rebind the key, my game crashed. The crash report is attached.
[crash-2022-04-14_10.00.58-server.txt](https://github.com/zPeanut/Hydrogen/files/8490871/crash-2022-04-14_10.00.58-server.txt)

**Comment by zPeanut** [comment] 2022-04-14 17:07
use .bind <module> <key> for now, ill look into this

**Comment by zPeanut** [comment] 2022-04-14 17:29
if the bind command still doesnt work (i've had problems sometimes assigning it to keys such as LCONTROL), you can change the clickgui bind manually in the modules.json folder located at ´.minecraft\Hydrogen\´, by searching for "ClickGUI" and changing the "keybind" value to 54.

it should look something like this:
![image](https://user-images.githubusercontent.com/25800857/163442153-92f71dfa-a5b2-47eb-9e8e-8399ce813213.png)

**Comment by Sobek88** [comment] 2022-04-14 23:16
Thanks!

**Comment by Sobek88** [comment] 2022-04-15 18:06
Update: the crash happening when I attempted to change the GUI keybind was a coincidence. The game just randomly crashes and says there was a ConcurrentModificationException. 

Here are three more crash logs:
[crash-2022-04-15_09.21.27-server.txt](https://github.com/zPeanut/Hydrogen/files/8497386/crash-2022-04-15_09.21.27-server.txt)
[crash-2022-04-15_09.28.48-server.txt](https://github.com/zPeanut/Hydrogen/files/8497387/crash-2022-04-15_09.28.48-server.txt)
[crash-2022-04-15_09.10.43-server.txt](https://github.com/zPeanut/Hydrogen/files/8497388/crash-2022-04-15_09.10.43-server.txt)

**Comment by zPeanut** [comment] 2022-04-15 18:33
this seems to be caused by a `ConcurrentModificationException`, meaning the module arraylist is being iterated through somewhere else.
this is fixed by synchronizing threads. i however have not been able to encounter this bug yet. if i (or you for that matter) can find a way to reproduce the bug 100% of the time (so i can check that its fully fixed), i can push a quick hotfix out.

**Comment by master7720** [comment] 2022-04-15 18:49
> I was testing the client in singleplayer Minecraft and noticed that the key to open up the GUI was LSHIFT. I tried to bind it to RSHIFT, which is the traditional GUI key, but when I attempted to rebind the key, my game crashed. The crash report is attached.
> [crash-2022-04-14_10.00.58-server.txt](https://github.com/zPeanut/Hydrogen/files/8490871/crash-2022-04-14_10.00.58-server.txt)

Wow your so smart your suppose to use it in MULTIPLAYER NOT SIGNLE PLAYER THATS WHY IT CRASHES

**Comment by zPeanut** [comment] 2022-04-15 18:52
lol it probably crashes in multiplayer too, its not related to SP or MP ?XD

**Comment by Sobek88** [comment] 2022-04-15 23:19
> Wow your so smart your suppose to use it in MULTIPLAYER NOT SIGNLE PLAYER THATS WHY IT CRASHES

BRO I WANTED TO TEST IT BEFORE HACKING ON NERDS IN COPS N' CRIMS

lmao skeletons can spawn on hypixel too so I'm gonna crash either way

**Comment by zPeanut** [comment] 2022-04-15 23:24
bro cops and crims is goated tho

**Comment by Sobek88** [comment] 2022-04-16 02:54
no one would be able to hit me bc i be zoomin xD

also esp op in cops and crims

**Comment by zPeanut** [comment] 2022-05-01 19:49
should be fixed in `1.12.4`

**Closed** 2022-05-01 19:49 UTC
Labels: bug
